services:
  redis:
    image: redis
    container_name: hotel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Volume này lưu trữ dữ liệu Redis (database)
    networks:
      - local

  redisinsight:
    image: redis/redisinsight:latest
    container_name: hotel-redisinsight
    ports:
      - "5540:5540"
    networks:
      - local
    depends_on:
      - redis


volumes:
  redis_data:

networks:
  local:
    driver: bridge
